import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container mx-auto ">
          <Navbar />
          <div className="h-[40rem] mt-4">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
